agents:
  queue: kubernetes
steps:
  - name: ":docker: Build test image"
    key: build-docker
    plugins:
      - kubernetes:
          podSpec:
            serviceAccount: ecr-push
            containers:
              - name: builder
                image: buildkite/agent:3.44.0
                command:
                  - scripts/ci/build_image.sh
                volumeMounts:
                  - name: buildkit-client
                    mountPath: /buildkit/certs
            volumes:
              - name: buildkit-client
                secret:
                  secretName: buildkit-client-certs
  - label: ":rspec:"
    depends_on: build-docker
    parallelism: 20
    env:
      RAILS_ENV: test
    plugins:
      - kubernetes:
          sidecars:
            - image: postgres:13
              env:
                - name: POSTGRES_PASSWORD
                  value: password
              args: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
            - image: redis:latest
            - image: tutum/memcached:latest
          podSpec:
            nodeSelector:
              kubernetes.io/arch: arm64
            serviceAccount: ecr-push
            containers:
              - name: app
                image: 253213882263.dkr.ecr.ap-southeast-2.amazonaws.com/rails-parallel-example:$BUILDKITE_COMMIT
                command:
                  - scripts/ci/parallel_specs.sh
