agents:
  queue: kubernetes
steps:
  - name: ":docker: Build test image"
    key: build-docker
    plugins:
      - kubernetes:
          podSpec:
            serviceAccount: ecr-push
            containers:
              - name: builder
                image: buildkite/agent:3.44.0
                command:
                  - scripts/ci/build_image.sh
                volumeMounts:
                  - name: buildkit-client
                    mountPath: /buildkit/certs
            volumes:
              - name: buildkit-client
                secret:
                  secretName: buildkit-client-certs
  - label: ":rspec:"
    depends_on: build-docker
    parallelism: 20
    env:
      RAILS_ENV: test
    command: scripts/ci/parallel_specs.sh
    plugins:
      - kubernetes:
          sidecars:
            - image: postgres:13
              env:
                - name: POSTGRES_PASSWORD
                  value: password
            - image: redis:latest
            - image: tutum/memcached:latest
          containers:
            podSpec:
              serviceAccount: ecr-push
              containers:
                - image: debian:latest
                  command:
                    - scripts/ci/parallel_specs.sh
