agents:
  queue: kubernetes
steps:
  - label: ":rspec:"
    parallelism: 20
    env:
      RAILS_ENV: test
    plugins:
      - kubernetes:
          sidecars:
            - image: postgres:13
              env:
                - name: POSTGRES_PASSWORD
                  value: password
            - image: redis:latest
            - image: tutum/memcached:latest
          containers:
            podSpec:
              - image: debian:latest
                command:
                  - scripts/ci/parallel_specs.sh
